//
//  ResponseKeys.swift
//  TWProjects
//
//  Created by Pritam Hinger on 14/09/16.
//  Copyright © 2016 AppDevelapp. All rights reserved.
//

import Foundation

extension TWProjectsClient{
    struct AccountResponseKeys {
        static let RealTimeNotifications = "realTimeNotifications"
        static let ShowSwitchToDotCom = "showSwitchToDotCom"
        static let DateSignedUp = "datesignedup"
        static let StrictBranding = "strictBranding"
        static let IsPaid = "isPaid"
        static let CanPreviewFiles = "canPreviewFiles"
        static let TouchIcon = "touchIcon"
        static let MarkdownEnabled = "markdownEnabled"
        static let Logo = "logo"
        static let ChatEnabled = "chatEnabled"
        static let Id = "id"
        static let TKOEnabled = "TKOEnabled"
        static let TagsEnabled = "tagsEnabled"
        static let ShowSiteNameOnLogin = "showSiteNameOnLogin"
        static let PricePlan = "pricePlan"
        static let AllowProjectAdminsCreateUsers = "allowProjectAdminsCreateUsers"
        static let PricePlanBranding = "priceplanBranding"
        static let CanEditCustomDomain = "canEditCustomDomain"
        static let Code = "code"
        static let Requirehttps = "requirehttps"
        static let Name = "name"
        static let UserIsAdmin = "userIsAdmin"
        static let TrialExpiryDate = "trialExpiryDate"
        static let CompanyName = "companyname"
        static let CanShareFiles = "canShareFiles"
        static let DocumentEditorEnabled = "documentEditorEnabled"
        static let CustomCSSEnabled = "customCSSEnabled"
        static let PaymentStatus = "paymentStatus"
        static let CacheUUID = "cacheUUID"
        static let OnTeamworkDomain = "onTeamworkDomain"
        static let DocumentEditorAvailable = "documentEditorAvailable"
        static let AllowKeepMeLoggedIn = "allowKeepMeLoggedIn"
        static let WebhooksEnabled = "webhooksEnabled"
        static let EmailNotificationEnabled = "email-notification-enabled"
        static let CompanyId = "companyid"
        static let PasswordPolicyIsOn = "passwordPolicyIsOn"
        static let NotebooksNewlineMode = "notebooksNewlineMode"
        static let RSSEnabled = "RSSEnabled"
        static let DashboardMessage = "dashboardMessage"
        static let TagsLockedToAdmins = "tagsLockedToAdmins"
        static let PricePlanId = "pricePlanId"
        static let PricePlanAllowSSL = "priceplanAllowSSL"
        static let FavIcon = "favIcon"
        static let AccountHolderId = "account-holder-id"
        static let URL = "URL"
        static let CleanNotebooksOnPaste = "cleanNotebooksOnPaste"
        static let TimeTrackingEnabled = "time-tracking-enabled"
        static let PDFServerLink = "pdfServerLink"
        static let DashboardProjectsList = "dashboardProjectsList"
        static let MemberOfOwnerCompany = "memberOfOwnerCompany"
        static let DashboardMessageHTML = "dashboardMessageHTML"
        static let SSLEnabled = "ssl-enabled"
        static let AllowTeamworkProjectsBrand = "allowTeamworkProjectsBrand"
        static let CreatedAt = "created-at"
        static let ProjectsEnabled = "projectsEnabled"
        static let IsAdmin = "isAdmin"
        static let DeskEnabled = "deskEnabled"
        static let CustomCSS = "customCSS"
        static let LikesEnabled = "likesEnabled"
        static let Lang = "lang"
        static let Status = "STATUS"
        static let Account = "account"
    }
    
    struct CompanyResponseKeys {
        static let State = "state"
        static let Name = "name"
        static let AddressTwo = "address_two"
        static let EmailOne = "email_one"
        static let Country = "country"
        static let IsOwner = "isowner"
        static let EmailThree = "email_three"
        static let Contacts = "contacts"
        static let Industry = "industry"
        static let LogoURL = "logo-URL"
        static let AddressOne = "address_one"
        static let Website = "website"
        static let CId = "cid"
        static let EmailTwo = "email_two"
        static let Accounts = "accounts"
        static let Phone = "phone"
        static let CompanyNameUrl = "company_name_url"
        static let CountryCode = "countrycode"
        static let CanSeePrivate = "can_see_private"
        static let Zip = "zip"
        static let Id = "id"
        static let City = "city"
        static let Fax = "fax"
        static let Status = "STATUS"
        static let Companies = "companies"
    }
    
    struct ProjectResponseKeys {
        static let Starred = "starred"
        static let ReplyByEmailEnabled = "replyByEmailEnabled"
        static let ShowAnnouncement = "show-announcement"
        static let HarvestTimersEnabled = "harvest-timers-enabled"
        static let Status = "status"
        static let SubStatus = "subStatus"
        static let DefaultPrivacy = "defaultPrivacy"
        static let CreatedOn = "created-on"
        static let FilesAutoNewVersion = "filesAutoNewVersion"
        static let Tags = "tags"
        static let Logo = "logo"
        static let StartDate = "startDate"
        static let Id = "id"
        static let LastChangedOn = "last-changed-on"
        static let EndDate = "endDate"
        static let Name = "name"
        static let PrivacyEnabled = "privacyEnabled"
        static let Description = "description"
        static let Announcement = "announcement"
        static let IsProjectAdmin = "isProjectAdmin"
        static let StartPage = "start-page"
        static let NotifyEveryone = "notifyeveryone"
        static let AnnouncementHTML = "announcementHTML"
        static let ResponseStatus = "STATUS"
        static let Projects = "projects"
    }
    
    struct  AuthenticateResponseKeys {
        static let UserIsMemberOfOwnerCompany = "userIsMemberOfOwnerCompany"
        static let TagsLockedToAdmins = "tagsLockedToAdmins"
        static let FirstName = "firstname"
        static let DateSeperator = "dateSeperator"
        static let Logo = "logo"
        static let ChatEnabled = "chatEnabled"
        static let Id = "id"
        static let StartOnSundays = "startonsundays"
        static let TKOEnabled = "TKOEnabled"
        static let TagsEnabled = "tagsEnabled"
        static let URL = "URL"
        static let DateFormat = "dateFormat"
        static let Code = "code"
        static let RequireHTTPS = "requirehttps"
        static let CanAddProjects = "canaddprojects"
        static let Name = "name"
        static let UserIsAdmin = "userIsAdmin"
        static let CompanyName = "companyname"
        static let CanManagePeople = "canManagePeople"
        static let SSLEnabled = "ssl-enabled"
        static let DocumentEditorEnabled = "documentEditorEnabled"
        static let ProjectsEnabled = "projectsEnabled"
        static let TimeFormat = "timeFormat"
        static let AvatarURL = "avatar-url"
        static let DeskEnabled = "deskEnabled"
        static let LikesEnabled = "likesEnabled"
        static let CompanyId = "companyid"
        static let Lang = "lang"
        static let LastName = "lastname"
        static let UserId = "userId"
        static let PlanId = "plan-id"
        static let Status = "STATUS"
        static let Account = "account"
    }
}